name: Build & Test

on:
  push:
  pull_request:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Setup Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Cache Nix store
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/nix
            /nix/store
          key: ${{ runner.os }}-nix-${{ hashFiles('**/flake.lock') }}
          restore-keys: |
            ${{ runner.os }}-nix-

      - name: Cache server dependencies
        uses: actions/cache@v3
        with:
          path: |
            server/deps
            server/_build
          key: ${{ runner.os }}-server-${{ hashFiles('server/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-server-

      - name: Cache client dependencies
        uses: actions/cache@v3
        with:
          path: |
            client/target
          key: ${{ runner.os }}-client-${{ hashFiles('client/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-client-

      - name: Cache worker dependencies
        uses: actions/cache@v3
        with:
          path: |
            worker/target
          key: ${{ runner.os }}-worker-${{ hashFiles('worker/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-worker-

      - name: Install Elixir dependencies
        run: |
          nix develop --command bash -c "cd server && mix deps.get"

      - name: Check formatting
        run: |
          nix develop --command bash -c "cd server && mix format --check-formatted"

      - name: Run tests
        run: |
          nix develop --command bash -c "cd server && mix test"

      - name: Build worker
        run: |
          nix develop --command bash -c "cd worker && cargo build --release"

      - name: Build client
        run: |
          nix develop --command bash -c "cd client && cargo build --release"
