name: Build and Test

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Build Server
        run: |
          nix build .#server -L

      - name: Test Server
        run: |
          cd server
          nix develop --command bash -c "mix deps.get && mix test"

      - name: Build Worker
        run: |
          nix build .#worker -L

      - name: Build Client
        run: |
          nix build .#client -L
