name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.ref_name == 'main' && github.sha || 'anysha' }}
  cancel-in-progress: true

jobs:
  build-nix-env:
    name: Check Nix Env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Restore Nix Store Cache
        uses: actions/cache@v4
        with:
          path: /nix/store
          key: ${{ runner.os }}-nix-${{ hashFiles('flake.lock') }}
          restore-keys: ${{ runner.os }}-nix-

      - name: Build Nix Flake
        run: nix develop --command "exit"

  # build-and-test:
  #   name: Build and Test
  #   runs-on: ubuntu-latest
  #   needs: [build-nix]
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Install Nix
  #       uses: cachix/install-nix-action@v30
  #       with:
  #         nix_path: nixpkgs=channel:nixos-unstable

  #     - name: Setup Nix Cache
  #       uses: DeterminateSystems/magic-nix-cache-action@v8

  #     - name: Build Server
  #       run: |
  #         nix build .#server -L

  #     - name: Test Server
  #       run: |
  #         cd server
  #         nix develop --command bash -c "mix deps.get && mix test"

  #     - name: Build Worker
  #       run: |
  #         nix build .#worker -L

  #     - name: Build Client
  #       run: |
  #         nix build .#client -L
